name: correlation_exploration
channels:
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.1.0
  - automat=0.7.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=2.1.3
  - bokeh=0.13.0
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.4.16
  - cffi=1.11.5
  - click=6.7
  - cloudpickle=0.5.3
  - constantly=15.1.0
  - cryptography=2.2.2
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=0.18.2
  - dask-core=0.18.2
  - dask-glm=0.1.0
  - dask-ml=0.7.0
  - dask-searchcv=0.2.0
  - decorator=4.3.0
  - distributed=1.22.0
  - entrypoints=0.2.3
  - expat=2.2.5
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.4
  - gettext=0.19.8.1
  - glib=2.56.1
  - graphite2=1.3.11
  - graphviz=2.40.1
  - harfbuzz=1.7.6
  - heapdict=1.0.0
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - incremental=17.5.0
  - intel-openmp=2018.0.3
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.3.0
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - jupyterlab=0.32.1
  - jupyterlab_launcher=0.10.5
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.34
  - libsodium=1.0.16
  - libtiff=4.0.9
  - libxml2=2.9.8
  - locket=0.2.0
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - mkl=2018.0.3
  - mkl_fft=1.0.2
  - mkl_random=1.0.1
  - msgpack-python=0.5.6
  - multipledispatch=0.5.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.1
  - notebook=5.6.0
  - numpy=1.14.5
  - numpy-base=1.14.5
  - openssl=1.0.2o
  - packaging=17.1
  - pandas=0.23.3
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - pango=1.42.1
  - parso=0.3.1
  - partd=0.3.8
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - pixman=0.34.0
  - prometheus_client=0.2.0
  - prompt_toolkit=1.0.15
  - psutil=5.4.6
  - ptyprocess=0.6.0
  - pyasn1=0.4.3
  - pyasn1-modules=0.2.2
  - pycparser=2.18
  - pygments=2.2.0
  - pygraphviz=1.3
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - python=3.6.6
  - python-dateutil=2.7.3
  - python.app=2
  - pytz=2018.5
  - pyyaml=3.13
  - pyzmq=17.0.0
  - readline=7.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=39.2.0
  - simplegeneric=0.8.1
  - six=1.11.0
  - sortedcontainers=2.0.4
  - sqlite=3.24.0
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - toolz=0.9.0
  - tornado=5.0.2
  - traitlets=4.3.2
  - twisted=17.5.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - widgetsnbextension=3.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
  - pip:
    - chardet==3.0.4
    - plotly==3.0.0rc11
    - requests==2.19.1
    - retrying==1.3.3
    - urllib3==1.23
prefix: /Users/solinjp1/anaconda3/envs/correlation_exploration
